{
  id: "camisa-box",
  name: "Camisa Box",
  image: undefined,
  imageLabel: "Camisa Box",
},
{
  id: "camisa-torcida-preta",
  name: "Camisa Torcida Preta",
  image: "/camisa-torcida-preta.jpeg",
  imageLabel: "Camisa Torcida Preta",
},
{
  id: "camisa-torcida-branca",
  name: "Camisa Torcida Branca",
  image: "/camisa-torcida-branca.jpeg",
  imageLabel: "Camisa Torcida Branca",
},
{
  id: "moletom",
  name: "Moletom Tuffão",
  image: "/moletom.jpeg",
  imageLabel: "Moletom Tuffão",
},
{
  id: "copo-termico",
  name: "Copo Térmico da Tuffão",
  image: "/copo-termico.jpeg",
  imageLabel: "Copo Térmico",
},
